services:
  - type: web
    name: duo-outbreak-marlinagency
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: corepack pnpm install --frozen-lockfile --prod=false && corepack pnpm build
    startCommand: corepack pnpm start:public
    envVars:
      - key: SERVE_CLIENT
        value: "1"
